### ISSUE TITLE
Update to v7.6.2

### ISSUE THREAD

**Issue by ivmai** [andyli/libatomic_ops-cygwin#1]
Hello Andy,

Could you please update VERSION to 7.6.2 in libatomic_ops.cygport and ask Cygwin guys to update the package?

BTW. "v7.4.6" in SRC_URI could be replaced to "v${VERSION}".

Thank you.

**Comment by andyli** [comment]
I've just uploaded the updated libatomic_ops to cygwin. It should be available very soon.
I will update libgc once the libatomic_ops update is live.

**Comment by ivmai** [comment]
Yes, they are updated now. Thank you.
Could you also please update mingw64 i686/x86_64 Cygwin packages?
